/**:
  ros__parameters:
    correlation_window_size: 15 # 35
    speckle_size: 250
    uniqueness_ratio: 15.0
    disparity_range: 128
    min_disparity: 25
    approximate_sync: True
    approximate_sync_tolerance_period: 0.05