/**:
  ros__parameters:
    leg_names: ['FL', 'RL', 'RR', 'FR']
    default_height: 0.175
    covariances: [0.01, 0.1, 0.05, 0.1, 0.1, 0.1]
    leg_command_rate: 50.0
    z_crouch: -0.105
    z_jump: -0.195
    time_crouch: 3.0
    time_hold: 1.5
    initial_jump_speed: 1.0
    mass: 10.0
    gravity: 1.15
    drag_coeff: 1.0