/**:
  ros__parameters:
    solve_frequency: 100.0
    window_size: 20
    time_step: 0.025
    leg_names: ['FL', 'RL', 'RR', 'FR']
    body_height: 0.18914
    gravity_vector: [0.0, 0.0, -9.81]
    body_mass: 23.0
    body_inertia: [0.25, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 1.0]
    friction_coefficient_x: 0.8
    force_z_min: 1.0
    force_z_max: 300.0
    linear_velocity_weights: [1.0, 1.0, 1.0]
    angular_velocity_weights: [1.0, 1.0, 1.0]
    force_weights: [0.000001, 0.000001]
    max_linear_velocity: [0.25, 0.0, 0.5]
    max_angular_velocity: [0.25, 0.1, 0.1]
    hip_locations: [0.3, 0.125, 0.0, -0.3, 0.125, 0.0, -0.3, -0.125, 0.0, 0.3, -0.125, 0.0]
    default_leg_positions: [0.0, 0.0, -0.18914, 0.0, 0.0, -0.18914, 0.0, 0.0, -0.18914, 0.0, 0.0, -0.18914]
    swing_resolution: 100
    step_height: 0.075
    swing_duration_factor: 0.75