/**:
  ros__parameters:
    leg_names: ['FL', 'RL', 'RR', 'FR']
    default_height: 0.175
    leg_command_rate: 250.0
    frequency: 3.5
    leg_length: 0.18
    z_amplitude: 0.005
    vel_amplitude_gain: 0.1
