/**:
  ros__parameters:
    leg_names: ['FL', 'RL', 'RR', 'FR']
    hip_positions: [1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0]
    min_velocity: 0.005
    min_radius: 0.5
    robot_width: 0.25
    leg_length: 0.2
    stride_resolution: 100
    step_height: 0.05
    duty_factor: 0.55
    max_stance_length: 0.15