/**:
  ros__parameters:
    leg_names: ['FL', 'RL', 'RR', 'FR']
    default_height: 0.175
    leg_command_rate: 250.0
    robot_width: 0.25
    center_shift: -0.5
    step_height: 0.015
    duty_factor: 0.50
    max_stance_length: 0.15