/**:
  ros__parameters:
    # use_sim_time: true
    leg_names: ['FL', 'RL', 'RR', 'FR']
    hip_positions: [1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0]
    robot_width: 0.25
    body_height: 0.175
    center_shift: -0.5
    stride_resolution: 100
    step_height: 0.015
    duty_factor: 0.50
    max_stance_length: 0.15