/**:
  ros__parameters:
    max_iterations: 100000
    max_generations: 1000
    time_limit_us: 10000000
    sample_time: 0.2
    grid_resolution: [0.1, 0.05, 0.1]
    max_velocities: [0.5, 0.25, 0.5]
    goal_threshold: 0.2
    solve_frequency: 10.0