/**:
  ros__parameters:
    i2c-bus: 7
    frequency: 20.0
    publish_depth_as_pose: true
    frame_id: 'bar100_link'
    fluid_density: 997.0474  # fresh water
    # fluid_density: 1023.6  # salt water
    gravity: 9.80665
    surface_pressure: 1.0
    variance: 2.89