/**:
  ros__parameters:
    num_cameras: 2
    min_num_images: 2
    sync_matching_threshold_ms: 20.0 # def: 5.0

    enable_image_denoising: true
    rectified_images: true
    enable_planar_mode: false
    enable_localization_n_mapping: true
    enable_imu_fusion: true

    # sigma_a is acclerometrer noise density
    # sigma_g is gyroscope noise density
    # accel_random_walk = 30 ug/sqrt(Hz)
    # gyro_random_walk = .14 deg/sqrt(h)\
    # accel_noise_density = 30 ug/sqrt(Hz)
    # gyro_noise_density = 8.5 deg/h/sqrt(Hz)
    gyro_noise_density : .0000412 # 1/sqrt(Hz)
    gyro_random_walk : .0000407 # 1/sqrt(Hz)
    accel_noise_density : .00000306 # 1/sqrt(Hz)
    accel_random_walk : .00000306 # 1/sqrt(Hz)
    calibration_frequncy: 200.0 # def: 200.0

    image_jitter_threshold_ms: 34.0 # def: 34.0
    imu_jitter_threshold_ms: 100.0 # default is 10

    img_mask_top: 0
    img_mask_bottom: 0
    img_mask_left: 0
    img_mask_right: 0

    map_frame: 'map'
    odom_frame: 'odom'
    base_frame: 'base_link'
    # camera_optical_frames: ['camera_left', 'camera_right']
    imu_frame: 'imu_link'

    image_buffer_size: 100 # def: 100
    imu_buffer_size: 50 # def: 50

    override_publishing_stamp: false
    publish_map_to_odom_tf: true
    publish_odom_to_rig_tf: true
    invert_map_to_odom_tf: false
    invert_odom_to_rig_tf: false

    enable_slam_visualization: true
    enable_observations_view: false
    enable_landmarks_view: true

    path_max_size: 1024
    verbosity: 3
    enable_debug_mode: false
    debug_dump_path: '/tmp/cuvslam'
    