ekf_node:
  ros__parameters:
    frequency: 100.0
    sensor_timeout: 0.1
    two_d_mode: false
    odom_frame: 'odom'
    base_link_frame: 'base_link'
    world_frame: 'odom'
    publish_tf: true

    # 15DOF State Vector:
    # [X    , Y     , Z
    #  Roll , Pitch , Yaw
    #  Vx   , Vy    , Vz
    #  Vroll, Vpitch, Vyaw
    #  Ax   , Ay    , Az  ]

    imu0: 'imu/data/calibrated' # imu_link frame
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  true, true, true]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: false

    pose0: 'bar100/pose' # odom frame
    pose0_config: [false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    pose0_queue_size: 10
    pose0_differential: false
    pose0_relative: false

    twist0: 'vel_estimate/stand'
    twist0_config: [false, false, false,
                    false, false, false,
                    true, true, true,
                    true, true, true,
                    false, false, false]
    twist0_queue_size: 10
    